irisToEmbed:
  - label:
      - http://www.w3.org/2000/01/rdf-schema#label
      - https://schema.org/name
      - http://schema.org/name
      - http://purl.org/dc/terms/title
      - http://purl.org/dc/elements/1.1/title
      - https://schema.org/title
      - http://schema.org/title
      - http://attribute.org/title
      - http://example.org/ontology/prefLabel
      - neo4j://graph.schema#name
      - http://www.w3.org/2004/02/skos/core#altLabel
      - http://purl.obolibrary.org/obo/IAO_0000118
      - http://qudt.org/schema/qudt/symbol
      - http://qudt.org/schema/qudt/ucumCode
      - http://qudt.org/schema/qudt/uneceCommonCode
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym
      - http://sail.ua.edu/ruralkg/administrativearea/name
      - http://sail.ua.edu/ruralkg/mentalhealthservice/name
      - http://sail.ua.edu/ruralkg/substanceabuse/name
      - http://sail.ua.edu/ruralkg/treatmentprovider/name
      - http://sail.ua.edu/ruralkg/treatmentprovider/alias
      - http://sail.ua.edu/ruralkg/administrativearea/abbreviation
      - https://idir.uta.edu/sockg-ontology/docs/bookName
      - https://idir.uta.edu/sockg-ontology/docs/citation
      - https://idir.uta.edu/sockg-ontology/docs/countyName
      - https://idir.uta.edu/sockg-ontology/docs/departmentName
      - https://idir.uta.edu/sockg-ontology/docs/experimentName
      - https://idir.uta.edu/sockg-ontology/docs/organizationName
      - https://idir.uta.edu/sockg-ontology/docs/projectName
      - https://idir.uta.edu/sockg-ontology/docs/title
      - https://idir.uta.edu/sockg-ontology/docs/firstName
      - https://idir.uta.edu/sockg-ontology/docs/middleName
      - https://idir.uta.edu/sockg-ontology/docs/lastName
  - subject:
      - http://purl.org/dc/terms/subject
      - https://schema.org/subject
      - http://schema.org/subject
  - description:
      - https://schema.org/description
      - http://schema.org/description
      - https://schema.org/disambiguatingDescription
      - http://schema.org/disambiguatingDescription
      - http://purl.obolibrary.org/obo/IAO_0000115
      - http://purl.org/dc/terms/description
      - http://purl.org/dc/elements/1.1/description
      - http://www.w3.org/2004/02/skos/core#definition
      - http://example.org/ontology/definition
      - http://qudt.org/schema/qudt/plainTextDescription
      - http://sail.ua.edu/ruralkg/mentalhealthservice/description
      - http://sail.ua.edu/ruralkg/settlementtype/description
      - http://schema.org/text
      - https://idir.uta.edu/sockg-ontology/docs/description
      - http://www.w3.org/2000/01/rdf-schema#comment
      - https://idir.uta.edu/sockg-ontology/docs/note
      - https://idir.uta.edu/sockg-ontology/docs/treatmentDescriptor
      - https://spec.industrialontologies.org/ontology/supplychain/SupplyChain/hasTextValue
