irisToEmbed:
  - label:
    - http://www.w3.org/2000/01/rdf-schema#label
    - https://schema.org/name
    - http://schema.org/name
    - http://purl.org/dc/terms/title
    - http://purl.org/dc/elements/1.1/title
    - http://www.w3.org/2004/02/skos/core#altLabel
  - subject:
    - http://purl.org/dc/terms/subject
    - https://schema.org/subject
    - http://schema.org/subject